apiVersion: v1
kind: Service
metadata:
  name: victoriatraces
spec:
  clusterIP: None
  selector:
    app: victoriatraces
  ports:
    - port: 10428
      name: http
    - port: 4317
      name: grpc
